gmtools/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from gmtools import views

app_name = "gmtools"

urlpatterns = [
    path(
        "translation_status/",
        views.TranslationStatusView.as_view(),
        name="translation_status",
    ),
    path(
        "template_statistics/",
        views.TemplateStatisticsView.as_view(),
        name="template_statistics",
    ),
    path(
        "roll_statistics/",
        views.RollStatisticsView.as_view(),
        name="roll_statistics",
    ),
    path(
        "extension_grid/<type>/",
        staff_member_required(views.ExtensionGrid.as_view()),
        name="extension_grid",
    ),
]

portal/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from portal import views

app_name = "portal"

urlpatterns = [
    path("profile/<int:pk>", views.ProfileView.as_view(), name="profile"),
    path(
        "profile/upload_image",
        views.ProfileUploadImageView.as_view(),
        name="upload_image",
    ),
    path("sidebar/search", views.SidebarSearchView.as_view(), name="search"),
    path(
        "wrapup/<int:pk>/<int:year>",
        cache_page(60 * 30)(views.YearlyWrapUpView.as_view()),
        name="wrapup",
    ),
    path("xhr/search", views.XhrSearchResultsView.as_view(), name="xhr_search_results"),
]

urpg/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.views.static import serve
from django_registration.backends.activation.views import RegistrationView

from characters.feeds import LatestModifiedAdmin, LatestNewAdmin
from portal.forms import CustomRegistrationForm
from portal.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("feeds/new_admin/", LatestNewAdmin()),
    path("feeds/modified_admin/", LatestModifiedAdmin()),
    path("", include("characters.urls", namespace="characters")),
    path("admin/", admin.site.urls),
    path(
        "contact/", TemplateView.as_view(template_name="contact.html"), name="contact"
    ),
    path("campaigns/", include("campaigns.urls", namespace="campaigns")),
    path("magic/", include("magic.urls", namespace="magic")),
    path("forum/", include("forum.urls", namespace="forum")),
    path("rulebook/", include("rulebook.urls", namespace="rulebook")),
    path("homebrew/", include("homebrew.urls", namespace="homebrew")),
    path("rules/", include("rules.urls", namespace="rules")),
    path("armory/", include("armory.urls", namespace="armory")),
    path("world/", include("worlds.urls", namespace="world")),
    path("gmtools/", include("gmtools.urls", namespace="gmtools")),
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        "accounts/register/",
        RegistrationView.as_view(form_class=CustomRegistrationForm),
        name="django_registration_register",
    ),
    path("accounts/", include("django_registration.backends.activation.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("portal/", include("portal.urls", namespace="portal")),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT})
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    if settings.DEBUG_TOOLBAR:
        urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

worlds/urls.py
from django.urls import path

from worlds import views

app_name = "worlds"

urlpatterns = [
    path(
        "foe_list",
        views.WikiPageWithGameValuesView.as_view(),
        name="wiki_page_with_game_values",
    ),
    path("", views.WorldListView.as_view(), name="list"),
    path("<str:slug>", views.WorldDetailView.as_view(), name="detail"),
    path(
        "<str:world_slug>/<str:slug>",
        views.WikiPageDetailView.as_view(),
        name="wiki_page",
    ),
    path(
        "<str:world_slug>/<str:slug>/edit",
        views.WikiPageEditTextView.as_view(),
        name="edit_text",
    ),
    path(
        "xhr_create/page/<int:world_pk>",
        views.XhrCreateWikiPageView.as_view(),
        name="xhr_create_wiki_page",
    ),
    path(
        "xhr_create/page/<int:world_pk>/<int:parent_pk>",
        views.XhrCreateWikiPageView.as_view(),
        name="xhr_create_wiki_page",
    ),
    # Sidebars
    path(
        r"sidebar/<str:slug>/<str:sidebar_template>/",
        views.XhrSidebarView.as_view(),
        name="xhr_sidebar",
    ),
    path(
        r"world_sidebar/<str:slug>/<str:sidebar_template>",
        views.XhrWorldSortSubPagesSidebarView.as_view(),
        name="xhr_world_sort_sidebar",
    ),
    path(
        r"wikipage_sidebar/<str:slug>/<str:sidebar_template>",
        views.XhrWikiPageSortSubPagesSidebarView.as_view(),
        name="xhr_wiki_page_sort_sidebar",
    ),
    path(
        "xhr_update_wiki_page_sort_order/<int:pk>/<str:model>",
        views.XhrUpdateItemSortOrderView.as_view(),
        name="xhr_update_wiki_page_sort_order",
    ),
    path(
        r"search_links/<str:world_slug>/",
        views.XhrSearchLinksView.as_view(),
        name="xhr_search_links",
    ),
    path(
        r"upload_image/<str:slug>/<str:kind>",
        views.XhrUploadImageView.as_view(),
        name="xhr_upload_image",
    ),
    path(
        r"additional_images/<str:slug>/",
        views.XhrAdditionalImagesView.as_view(),
        name="xhr_additional_images",
    ),
    path(
        r"xhr_auto_tag/<int:pk>/", views.XhrAutoTagView.as_view(), name="xhr_auto_tag"
    ),
]

portal/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from sorl.thumbnail import get_thumbnail

from characters.utils import static_thumbnail


class Profile(models.Model):
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)

    image = models.ImageField(
        _("image"), upload_to="profile_images", max_length=200, blank=True, null=True
    )
    image_copyright = models.CharField(
        _("image copyright"), max_length=40, blank=True, null=True
    )
    image_copyright_url = models.CharField(
        _("image copyright url"), max_length=150, blank=True, null=True
    )

    backdrop_image = models.ImageField(
        _("backdrop image"),
        upload_to="profile_backdrop_images",
        max_length=200,
        blank=True,
        null=True,
    )
    backdrop_copyright = models.CharField(
        _("image copyright"), max_length=40, blank=True, null=True
    )
    backdrop_copyright_url = models.CharField(
        _("image copyright url"), max_length=150, blank=True, null=True
    )

    bio = models.TextField(_("bio"), blank=True, null=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

    def get_image_url(self, geometry="180", crop="center"):
        if self.image:
            return get_thumbnail(self.image, geometry, crop=crop, quality=99).url

        return static_thumbnail(
            f"img/silhouette.png",
            geometry_string=geometry,
            crop=crop,
        )

    def get_backdrop_image_url(self, geometry="1800", crop="center"):
        if self.backdrop_image:
            return get_thumbnail(
                self.backdrop_image, geometry, crop=crop, quality=99
            ).url
        return static_thumbnail(
            f"img/header-background.png",
            geometry_string=geometry,
            crop=crop,
        )

portal/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django_registration.forms import RegistrationForm


class CustomRegistrationForm(RegistrationForm):
    email2 = forms.CharField(label=_("E-Mail"), max_length=100, required=False)

    def clean_email2(self):
        email2 = self.cleaned_data.get("email2")
        if email2:
            raise forms.ValidationError("Keine Eingabe.")
        return email2

portal/views.py
from django.contrib.auth.models import User
from django.db.models import Q, Count
from django.db.models.functions import Trunc, Length
from django.shortcuts import redirect
from django.templatetags.static import static
from django.views import View
from django.views.generic import TemplateView, DetailView

from campaigns.models import Roll, Campaign
from characters.models import Character
from portal.models import Profile
from worlds.models import WikiPage, WorldLeadImage, World


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_characters(self):
        context = {}
        characters = Character.objects.filter(image__isnull=False)

        lead_images = WorldLeadImage.objects.all()

        if self.request.world_configuration is not None:
            characters = characters.filter(
                extensions=self.request.world_configuration.world.extension
            )
            lead_images = lead_images.filter(
                world=self.request.world_configuration.world
            )
        if self.request.user.is_authenticated:
            characters = characters.filter(created_by=self.request.user).order_by(
                "-modified_at"
            )
        else:
            characters = characters.filter(may_appear_on_start_page=True).order_by("?")

        context["characters"] = characters[:3]
        try:
            context["lead_image"] = lead_images.order_by("?").first()
        except WorldLeadImage.DoesNotExist:
            context["lead_image"] = None
        return context

    def get_context_campaigns(self):
        context = {}
        campaigns = Campaign.objects.filter(image__isnull=False)
        if self.request.world_configuration is not None:
            campaigns = campaigns.filter(
                world=self.request.world_configuration.world.extension
            )

        if self.request.user.is_authenticated:
            campaigns = campaigns.filter(created_by=self.request.user).order_by(
                "-created_at"
            )
        else:
            campaigns = campaigns.filter(may_appear_on_start_page=True).order_by("?")
        context["campaigns"] = campaigns[:3]
        return context

    def get_context_worlds(self):
        context = {}
        if not self.request.world_configuration:
            context["worlds"] = World.objects.filter(is_active=True)
        return context

    def get_context_wiki_pages(self):
        context = {}
        if self.request.world_configuration is not None:
            world = self.request.world_configuration.world
            context["wiki_pages"] = (
                WikiPage.objects.annotate(text_len=Length("text_de"))
                .filter(world=world, text_len__gte=30)
                .order_by("?")[:3]
            )
        return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_context_characters())
        context.update(self.get_context_worlds())
        context.update(self.get_context_campaigns())
        context.update(self.get_context_wiki_pages())

        if self.request.world_configuration:
            world = self.request.world_configuration.world
            context["world"] = world
            context["may_edit"] = world.may_edit(self.request.user)
        else:
            context["world"] = None
            context["may_edit"] = False

        return context


class SidebarSearchView(TemplateView):
    template_name = "portal/sidebar/search.html"


class XhrSearchResultsView(TemplateView):
    template_name = "portal/sidebar/search_results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get("q", "")
        search_descriptions = self.request.GET.get("search_descriptions", "off")
        if query:
            if search_descriptions == "on":
                wiki_pages = WikiPage.objects.filter(
                    Q(name_en__icontains=query)
                    | Q(name_de__icontains=query)
                    | Q(text_en__icontains=query)
                    | Q(text_de__icontains=query)
                )
            else:
                wiki_pages = WikiPage.objects.filter(
                    Q(name_de__icontains=query) | Q(name_en__icontains=query)
                )

            if (
                self.request.world_configuration
                and self.request.world_configuration.world
            ):
                wiki_pages = wiki_pages.filter(
                    Q(world=self.request.world_configuration.world)
                )
            context["wiki_pages"] = wiki_pages

            if self.request.user.is_authenticated:
                context["characters"] = Character.objects.filter(
                    Q(created_by=self.request.user) | Q(created_by__isnull=True)
                ).filter(name__icontains=query)
        return context


class ProfileView(DetailView):
    template_name = "portal/profile.html"
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["may_edit"] = self.request.user == self.object
        return context


class ProfileUploadImageView(View):
    def post(self, request, *args, **kwargs):
        profile = Profile.objects.get(user=request.user)
        profile.image = request.FILES["image"]
        profile.save()
        return redirect("portal:profile", pk=request.user.id)


class YearlyWrapUpView(TemplateView):
    template_name = "portal/yearly_wrapup.html"

    def get_most_played(self, qs):
        res = []
        for mp in (
            qs.values("character")
            .annotate(total=Count("character"))
            .order_by("-total")[:3]
        ):
            character = Character.objects.get(id=mp["character"])
            days = self._get_days(qs, character)
            res.append((character, mp["total"], days))
        return res

    def get_played_campaigns(self, qs):
        return [
            (Campaign.objects.get(id=mp["campaign"]), mp["total"])
            for mp in qs.exclude(campaign__isnull=True)
            .values("campaign")
            .annotate(total=Count("campaign"))
            .order_by("-total")
        ]

    def get_highest_roll(self, qs, mode):
        try:
            return qs.order_by(f"-{mode}")[0]
        except IndexError:
            return None

    def get_platform_stats(self):
        qs = Roll.objects.filter(created_at__year=self.kwargs["year"])
        return {
            "platform_crit_count": self.get_highest_roll(qs, "crit_count"),
            "platform_exploded_dice_count": self.get_highest_roll(
                qs, "exploded_dice_count"
            ),
            "platform_successes_count": self.get_highest_roll(qs, "successes_count"),
            "platform_fails_count": self.get_highest_roll(qs, "fails_count"),
            "platform_highest_single_roll": self.get_highest_roll(
                qs, "highest_single_roll"
            ),
            "platform_total_sum": self.get_highest_roll(qs, "total_sum"),
            "platform_roll_count": qs.count(),
            "platform_days": self._get_days(qs),
            "platform_characters_created": Character.objects.filter(
                created_at__year=self.kwargs["year"]
            ).count(),
            "platform_campaigns_created": Campaign.objects.filter(
                created_at__year=self.kwargs["year"]
            ).count(),
        }

    def get_user_stats(self):
        qs = Roll.objects.filter(
            character__created_by=User.objects.get(id=self.kwargs["pk"]),
            created_at__year=self.kwargs["year"],
        )
        return {
            "wrapup_user": User.objects.get(id=self.kwargs["pk"]),
            "year": self.kwargs["year"],
            "qs": qs,
            "most_played": self.get_most_played(qs),
            "played_campaigns": self.get_played_campaigns(qs),
            "roll_crit_count": self.get_highest_roll(qs, "crit_count"),
            "roll_exploded_dice_count": self.get_highest_roll(
                qs, "exploded_dice_count"
            ),
            "roll_successes_count": self.get_highest_roll(qs, "successes_count"),
            "roll_fails_count": self.get_highest_roll(qs, "fails_count"),
            "roll_highest_single_roll": self.get_highest_roll(
                qs, "highest_single_roll"
            ),
            "roll_total_sum": self.get_highest_roll(qs, "total_sum"),
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_user_stats())
        context.update(self.get_platform_stats())
        context["header_image"] = static("img/wrapup_2024.png")
        if self.kwargs["year"] == 2023:
            context["header_image"] = static("img/wrapup_2023.png")
        return context

    def _get_days(self, qs, character=None):
        if character:
            qs = qs.filter(character=character)

        return (
            qs.annotate(created_at_day=Trunc("created_at", "day"))
            .values("created_at_day")
            .annotate(total=Count("created_at_day"))
            .count()
        )

portal/templates/portal/_bottom_navigation_button.html
<div id="bottom-nav-modal" class="modal fade page-modal" tabindex="-1" role="dialog"
     aria-labelledby="page-modal">
  <div class="modal-dialog modal-fullscreen" role="document">
    <div class="modal-content">
      <div class="modal-body">
        {% include template_include with object=object may_edit=may_edit %}
      </div>
    </div>
  </div>
</div>

<button data-bs-toggle="modal"
        data-bs-target="#bottom-nav-modal"
        class="btn btn-primary hover btn-circle d-block d-xl-none position-fixed bottom-0 end-0 z-3 me-2 me-md-4 mb-2 mb-md-4">
  <i class="fas fa-bars"></i>
</button>

portal/templates/portal/_navigation.html
{% load i18n %}
{% load portal_extras %}
<div class="list-group mb-3">
  <a class="active navigation-link pointer py-3 list-group-item list-group-item-action d-flex justify-content-between align-items-center"
     data-bs-toggle="tab"
     data-bs-target="#characters-tab-pane"
     role="tab"
     aria-current="true">
    <div class="d-flex justify-content-center align-items-center">
      <i class="fas fa-home"></i>
      <span class="ms-3 d-block d-lg-block">{% trans "Characters" %}</span>
    </div>
  </a>

  <a class="navigation-link pointer py-3 list-group-item list-group-item-action d-flex justify-content-between align-items-center"
     data-bs-toggle="tab"
     data-bs-target="#npc-tab-pane"
     role="tab"
     aria-current="true">
    <div class="d-flex justify-content-center align-items-center">
      <i class="fas fa-home"></i>
      <span class="ms-3 d-block d-lg-block">{% trans "NPC" %}</span>
    </div>
  </a>

  <a class="py-3 navigation-link pointer list-group-item list-group-item-action d-flex justify-content-between align-items-center"
     data-bs-toggle="tab"
     data-bs-target="#gm-campaigns-tab-pane"
     role="tab"
     aria-current="false">
    <div class="d-flex justify-content-center align-items-center">
      <i class="fas fa-home"></i>
      <span class="ms-3 d-block d-lg-block">{% trans "Campaigns" %}</span>
    </div>
  </a>

  <a class="py-3 navigation-link pointer list-group-item list-group-item-action d-flex justify-content-between align-items-center"
     data-bs-toggle="tab"
     data-bs-target="#more-tab-pane"
     role="tab"
     aria-current="false">
    <div class="d-flex justify-content-center align-items-center">
      <i class="fas fa-home"></i>
      <span class="ms-3 d-block d-lg-block">{% trans "More" %}</span>
    </div>
  </a>
</div>

{% if may_edit %}
  <div class="list-group mb-3">
    <div class="list-group-item py-3" role="button">
      <div class="d-flex align-items-center">
        <i class="fas fa-fw fa-pen"></i>
        <form action="{% url "portal:upload_image" %}" method="post" id="profile-image-form"
              enctype="multipart/form-data">
          {% csrf_token %}
          <input type="file" name="image" id="id_profile_image_upload" class="d-none">
        </form>
        <span class="ms-3 d-block profile-image-upload-button d-lg-block">{% trans "Upload Image" %}</span>
      </div>
    </div>
  </div>
{% endif %}

portal/templates/portal/_yearly_wrapup_roll_tile.html
{% load thumbnail static i18n %}
{% if roll %}
  <div class="d-flex flex-column align-items-center my-2 mx-1">
    {% with character=roll.character %}
      <a href="{% url "characters:detail" pk=character.id %}" class="no-decoration no-link-colors">
        {% if character.image %}
          {% thumbnail character.image "400x400" crop="center" as im %}
            <img class="img-fluid rounded float-start me-3"
                 src="{{ im.url }}"
                 alt="{{ character.name }}">
          {% endthumbnail %}
        {% else %}
          <img class="img-fluid rounded float-start me-3"
               height="400" width="400"
               src="{% static 'img/silhuette.png' %}"
               alt="{{ character.name }}">
        {% endif %}
      </a>
    {% endwith %}
    <div class="fs-3">{{ roll_text }}</div>
    <div class="fs-4 mt-2">{{ roll.header }}</div>
    <div class="fs-5">{{ roll.created_at|date:"d.m.Y H:i" }}</div>
    {% include "campaigns/_dice_socket_results.html" with roll=roll %}
  </div>
{% endif %}

portal/templates/portal/profile.html
{% extends 'base.html' %}
{% load characters_extras %}
{% load campaign_extras %}
{% load portal_extras %}
{% load i18n %}
{% load static %}

{% block title %}{{ object.username|capfirst }} - {{ block.super }}{% endblock %}
{% block in_page_title %}{{ object.username|capfirst }}{% endblock %}
{% block in_page_subtitle %}{% trans "Member since" %} {{ object.date_joined|date:"Y" }}{% endblock %}

{% block bottom_nav %}
  {% bottom_navigation_button "portal/_navigation.html" %}
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/profile.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-12 col-xl-3 d-none d-xl-block">
      {% include "portal/_navigation.html" with object=object %}
    </div>

    <div class="col-12 col-xl-9">
      <div class="tab-content">

        <div class="tab-pane fade show active" id="characters-tab-pane" role="tabpanel" tabindex="0">
          <div class="row character-list">

            {% if may_edit %}
              <div class="col-12 col-sm-6 col-md-4 mb-3">
                {% create_character_url as create_url %}
                <a href="{{ create_url }}">
                  <div class="card d-flex justify-content-center align-items-center mb-2 h-100">
                    <i class="fas fa-plus fa-2x"></i>
                    <span class="invite-text">{% trans "Create Character" %}</span>
                  </div>
                </a>
              </div>
            {% endif %}

            {% for character in object.character_set.pc|for_world_configuration:request.world_configuration %}
              <div class="col-12 col-sm-6 col-md-4 mb-3">
                {% include 'characters/_character_list_widget.html' with character=character %}
              </div>
            {% endfor %}
          </div>
        </div>

        <div class="tab-pane fade" id="npc-tab-pane" role="tabpanel" tabindex="0">
          <div class="row character-list">
            {% for character in object.character_set.npc|for_world_configuration:request.world_configuration %}
              <div class="col-12 col-sm-6 col-md-4 mb-3">
                {% include 'characters/_character_list_widget.html' with character=character %}
              </div>
            {% endfor %}
          </div>
        </div>

        <div class="tab-pane fade" id="gm-campaigns-tab-pane" role="tabpanel" tabindex="0">
          <div class="row campaign-list">

            {% if may_edit %}
              {% create_campaign_url as create_url %}
              <div class="col-12 col-md-6 mb-3">
                <a href="{{ create_url }}">
                  <div class="card d-flex justify-content-center align-items-center mb-2 h-100">
                    <i class="fas fa-plus fa-2x"></i>
                    <span class="invite-text">{% trans "Create Campaign" %}</span>
                  </div>
                </a>
              </div>
            {% endif %}

            {% for campaign in object.campaign_set.all|for_world_configuration:request.world_configuration %}
              <div class="col-12 col-md-6 mb-3">
                {% include 'campaigns/_campaign_list_widget.html' with campaign=campaign %}
              </div>
            {% endfor %}
          </div>
        </div>

        <div class="tab-pane fade" id="more-tab-pane" role="tabpanel" tabindex="0">
          <div class="row">

            {% if request.user.is_superuser and may_edit %}
              <div class="col-12 col-md-6 mb-3">
                <a href="{% url 'admin:index' %}" class="no-decoration">
                  <div class="position-relative profile-cta">
                    <img src="{% static "img/profile_cta_images/profile_admin.png" %}" alt="admin"
                         class="img img-fluid rounded">
                    <div class="profile-cta-text w-100 p-2">{% trans "Admin" %}</div>
                  </div>
                </a>
              </div>
            {% endif %}

            <div class="col-12 col-md-6 mb-3">
              <a href="{% url "portal:wrapup" pk=object.id year=2024 %}" class="no-decoration">
                <div class="position-relative profile-cta">
                  <img src="{% static "img/profile_cta_images/profile_wrapup_2024.png" %}" alt="wrapup"
                       class="img img-fluid rounded">
                  <div class="profile-cta-text w-100 p-2">{% trans "2024 WrapUp" %}</div>
                </div>
              </a>
            </div>

            <div class="col-12 col-md-6 mb-3">
              <a href="{% url "portal:wrapup" pk=object.id year=2023 %}" class="no-decoration">
                <div class="position-relative profile-cta">
                  <img src="{% static "img/profile_cta_images/profile_wrapup_2023.png" %}" alt="wrapup"
                       class="img img-fluid rounded">
                  <div class="profile-cta-text w-100 p-2">{% trans "2023 WrapUp" %}</div>
                </div>
              </a>
            </div>

            {% if request.user.is_superuser and may_edit %}
              <div class="col-12 col-md-6 mb-3">
                <a href="{% url 'gmtools:extension_grid' type='riotgear' %}" class="no-decoration">
                  <div class="position-relative profile-cta">
                    <img src="{% static "img/profile_cta_images/profile_extension_grid.png" %}"
                         alt="admin"
                         class="img img-fluid rounded">
                    <div class="profile-cta-text w-100 p-2">{% trans "Extension Grids" %}</div>
                  </div>
                </a>
              </div>
            {% endif %}

            <div class="col-12 col-md-6 mb-3">
              <a href="{% url 'gmtools:template_statistics' %}" class="no-decoration">
                <div class="position-relative profile-cta">
                  <img src="{% static "img/profile_cta_images/profile_template_statistics.png" %}"
                       alt="admin"
                       class="img img-fluid rounded">
                  <div class="profile-cta-text w-100 p-2">{% trans "Template Statistics" %}</div>
                </div>
              </a>
            </div>

            <div class="col-12 col-md-6 mb-3">
              <a href="{% url 'gmtools:translation_status' %}" class="no-decoration">
                <div class="position-relative profile-cta">
                  <img src="{% static "img/profile_cta_images/profile_translation_status.png" %}"
                       alt="admin"
                       class="img img-fluid rounded">
                  <div class="profile-cta-text w-100 p-2">{% trans "Translation Status" %}</div>
                </div>
              </a>
            </div>

            {% if request.user.is_superuser and may_edit %}
              <div class="col-12 col-md-6 mb-3">
                <a href="{% url 'homebrew:index' %}" class="no-decoration">
                  <div class="position-relative profile-cta">
                    <img src="{% static "img/profile_cta_images/profile_homebrew_review.png" %}"
                         alt="admin"
                         class="img img-fluid rounded">
                    <div class="profile-cta-text w-100 p-2">{% trans "Review Homebrew" %}</div>
                  </div>
                </a>
              </div>
            {% endif %}

            <div class="col-12 col-md-6 mb-3">
              <a href="{% url "gmtools:roll_statistics" %}" class="no-decoration">
                <div class="position-relative profile-cta">
                  <img src="{% static "img/profile_cta_images/profile_roll_statistics.png" %}"
                       alt="admin"
                       class="img img-fluid rounded">
                  <div class="profile-cta-text w-100 p-2">{% trans "Roll Statistics" %}</div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}