campaigns/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from campaigns import views

app_name = "campaigns"

urlpatterns = [
    path("new/", login_required(views.CreateCampaignView.as_view()), name="create"),
    path(
        "new/<int:world_pk>/",
        views.CreateCampaignEpochView.as_view(),
        name="create_epoch",
    ),
    path(
        "new/<int:world_pk>/<int:epoch_pk>)/",
        views.CreateCampaignExtensionsView.as_view(),
        name="create_extensions",
    ),
    path(
        "new/data/<int:world_pk>/<int:epoch_pk>/",
        views.CreateCampaignDataView.as_view(),
        name="create_data",
    ),
    path("detail/<int:pk>", views.CampaignDetailView.as_view(), name="detail"),
    path(
        "detail/<int:pk>/invite/<hash>",
        views.CampaignDetailView.as_view(),
        name="detail",
    ),
    path(
        "detail/settings/<int:pk>",
        views.SaveSettingsView.as_view(),
        name="save_settings",
    ),
    path("dice_log/<int:pk>", views.XhrDiceLogView.as_view(), name="xhr_dice_log"),
    path(
        "xhr_campaign_fragment/<int:pk>/<fragment_template>",
        views.XhrCampaignFragmentView.as_view(),
        name="xhr_campaign_fragment",
    ),
    path(
        "remove_character/<int:pk>/<int:character_pk>",
        views.XhrRemoveCharacterView.as_view(),
        name="xhr_remove_character",
    ),
    path(
        "switch_npc/<int:pk>/<int:character_pk>",
        views.XhrSwitchCharacterNPCView.as_view(),
        name="xhr_switch_npc",
    ),
    path(
        "add_foe/<int:pk>/<int:wiki_page_pk>",
        views.XhrAddFoeToCampaignView.as_view(),
        name="xhr_add_foe",
    ),
    path(
        "remove_foe/<int:pk>/<int:foe_pk>",
        views.XhrRemoveFoeView.as_view(),
        name="xhr_remove_foe",
    ),
    path(
        "search_foe/<int:pk>",
        views.XhrSearchFoeSidebarView.as_view(),
        name="xhr_search_foe",
    ),
    path(
        "sidebar/<int:pk>/<sidebar_template>",
        views.XhrSidebarView.as_view(),
        name="xhr_sidebar",
    ),
    path(
        "sidebar/settings/<int:pk>/<sidebar_template>",
        views.XhrSettingsSidebarView.as_view(),
        name="xhr_settings_sidebar",
    ),
    path(
        "sidebar/character/<int:pk>/<sidebar_template>",
        views.XhrCharacterSidebarView.as_view(),
        name="xhr_character_sidebar",
    ),
    path(
        "sidebar/foe/<int:pk>/<sidebar_template>",
        views.XhrFoeSidebarView.as_view(),
        name="xhr_foe_sidebar",
    ),
    path(
        "game_log/<int:campaign_pk>",
        views.XhrCampaignGameLogView.as_view(),
        name="xhr_game_log",
    ),
    # Statistics
    path(
        "statistics/<int:pk>/<str:mode>",
        views.XhrCampaignStatisticsView.as_view(),
        name="xhr_statistics",
    ),
]

homebrew/urls.py
from django.urls import path

from homebrew import views

app_name = "homebrew"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("xhr_create/item", views.XhrCreateItemView.as_view(), name="xhr_create_item"),
    path("create/item", views.CreateItemView.as_view(), name="create_item"),
    path(
        "xhr_create/riot_gear",
        views.XhrCreateRiotGearView.as_view(),
        name="xhr_create_riot_gear",
    ),
    path(
        "create/riot_gear", views.CreateRiotGearView.as_view(), name="create_riot_gear"
    ),
    path(
        "xhr_create/weapon",
        views.XhrCreateWeaponView.as_view(),
        name="xhr_create_weapon",
    ),
    path("create/weapon", views.CreateWeaponView.as_view(), name="create_weapon"),
    path(
        "xhr_create/basespell",
        views.XhrCreateBaseSpellView.as_view(),
        name="xhr_create_base_spell",
    ),
    path(
        "create/basespell",
        views.CreateBaseSpellView.as_view(),
        name="create_base_spell",
    ),
]

urpg/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.views.static import serve
from django_registration.backends.activation.views import RegistrationView

from characters.feeds import LatestModifiedAdmin, LatestNewAdmin
from portal.forms import CustomRegistrationForm
from portal.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("feeds/new_admin/", LatestNewAdmin()),
    path("feeds/modified_admin/", LatestModifiedAdmin()),
    path("", include("characters.urls", namespace="characters")),
    path("admin/", admin.site.urls),
    path(
        "contact/", TemplateView.as_view(template_name="contact.html"), name="contact"
    ),
    path("campaigns/", include("campaigns.urls", namespace="campaigns")),
    path("magic/", include("magic.urls", namespace="magic")),
    path("forum/", include("forum.urls", namespace="forum")),
    path("rulebook/", include("rulebook.urls", namespace="rulebook")),
    path("homebrew/", include("homebrew.urls", namespace="homebrew")),
    path("rules/", include("rules.urls", namespace="rules")),
    path("armory/", include("armory.urls", namespace="armory")),
    path("world/", include("worlds.urls", namespace="world")),
    path("gmtools/", include("gmtools.urls", namespace="gmtools")),
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        "accounts/register/",
        RegistrationView.as_view(form_class=CustomRegistrationForm),
        name="django_registration_register",
    ),
    path("accounts/", include("django_registration.backends.activation.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("portal/", include("portal.urls", namespace="portal")),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT})
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    if settings.DEBUG_TOOLBAR:
        urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

campaigns/models.py
import hashlib

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from sorl.thumbnail import get_thumbnail

from characters.utils import static_thumbnail
from rules.models import Extension


class CampaignQuerySet(models.QuerySet):
    def for_world_configuration(self, world_configuration):
        if world_configuration is not None:
            return self.filter(world=world_configuration.world.extension)
        return self.all()


class Campaign(models.Model):
    VISIBILITY_CHOICES = (
        ("G", _("GM Only")),
        ("A", _("All")),
    )

    objects = CampaignQuerySet.as_manager()

    name = models.CharField(_("name"), max_length=80)
    image = models.ImageField(
        _("image"), upload_to="campaign_images", max_length=200, blank=True, null=True
    )
    image_copyright = models.CharField(
        _("image copyright"), max_length=40, blank=True, null=True
    )
    image_copyright_url = models.CharField(
        _("image copyright url"), max_length=150, blank=True, null=True
    )

    may_appear_on_start_page = models.BooleanField(
        _("may appear on start page"),
        help_text=_(
            "This campaign may appear on the anonymous start page (i.E. if it has only free images"
        ),
        default=False,
    )

    backdrop_image = models.ImageField(
        _("backdrop image"),
        upload_to="campaign_backdrop_images",
        max_length=200,
        blank=True,
        null=True,
    )
    backdrop_copyright = models.CharField(
        _("image copyright"), max_length=40, blank=True, null=True
    )
    backdrop_copyright_url = models.CharField(
        _("image copyright url"), max_length=150, blank=True, null=True
    )
    abstract = models.TextField(_("abstract"), blank=True, null=True)

    created_by = models.ForeignKey(
        "auth.User", verbose_name=_("created by"), on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)

    epoch = models.ForeignKey(
        "rules.Extension",
        limit_choices_to={"type": "e", "is_mandatory": False},
        on_delete=models.CASCADE,
        related_name="campaign_epoch_set",
        verbose_name=_("Epoch"),
    )
    world = models.ForeignKey(
        "rules.Extension",
        limit_choices_to={"type": "w", "is_mandatory": False},
        on_delete=models.CASCADE,
        related_name="campaign_world_set",
        verbose_name=_("World"),
    )
    extensions = models.ManyToManyField(
        "rules.Extension",
        limit_choices_to={"is_mandatory": False, "type": "x"},
        blank=True,
    )
    forbidden_templates = models.ManyToManyField("rules.Template", blank=True)
    starting_template_points = models.IntegerField(
        _("additional starting career points"), default=0
    )

    discord_webhook_url = models.URLField(
        _("discord webhook url"),
        max_length=256,
        help_text=_(
            "Create a discord webhook and paste it's url here to display dice results."
        ),
        blank=True,
        null=True,
    )

    currency_map = models.ForeignKey("armory.CurrencyMap", on_delete=models.CASCADE)
    seed_money = models.IntegerField(_("seed money"), default=2000)

    foe_visibility = models.CharField(
        _("foe visibility"), max_length=1, default="A", choices=VISIBILITY_CHOICES
    )

    npc_visibility = models.CharField(
        _("npc visibility"), max_length=1, default="A", choices=VISIBILITY_CHOICES
    )

    game_log_visibility = models.CharField(
        _("game log visibility"), max_length=1, default="A", choices=VISIBILITY_CHOICES
    )

    character_visibility = models.CharField(
        _("character visibility"), max_length=1, default="A", choices=VISIBILITY_CHOICES
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("campaigns:detail", kwargs={"pk": self.id})

    def may_edit(self, user):
        if self.created_by == user:
            return True
        return False

    @property
    def extension_string(self):
        return ", ".join([e.name for e in self.extensions.all()])

    @property
    def campaign_hash(self):
        return hashlib.sha256(
            "{}{}{}{}".format(
                self.id, self.created_at, self.name, self.created_by.id
            ).encode("utf-8")
        ).hexdigest()

    @property
    def invite_link(self):
        return settings.BASE_URL + reverse(
            "campaigns:detail", kwargs={"pk": self.id, "hash": self.campaign_hash}
        )

    def get_image_url(self, geometry="180", crop="center"):
        if self.image:
            return get_thumbnail(self.image, geometry, crop=crop, quality=99).url

        return static_thumbnail(
            f"img/silhouette.png",
            geometry_string=geometry,
            crop=crop,
        )

    def get_backdrop_image_url(self, geometry="600x160", crop="center"):
        image = self.epoch.image
        if self.world.image:
            image = self.world.image
        if self.backdrop_image:
            image = self.backdrop_image

        return get_thumbnail(image, geometry, crop=crop, quality=99).url

    @property
    def ws_room_name(self) -> str:
        """Websocket room name"""
        return f"campaign-{self.id}"


class Foe(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    wiki_page = models.ForeignKey("worlds.WikiPage", on_delete=models.CASCADE)

    def may_edit(self, user):
        return self.campaign.may_edit(user)


class Scene(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    name = models.CharField(_("name"), max_length=80)
    text = models.TextField(_("text"), blank=True, null=True)

    npc = models.ManyToManyField("characters.Character")


class Handout(models.Model):
    scene = models.ForeignKey(Scene, on_delete=models.CASCADE)
    name = models.CharField(_("name"), max_length=80)
    image = models.ImageField(
        _("image"), upload_to="campaign_handouts", max_length=200, blank=True, null=True
    )
    image_copyright = models.CharField(
        _("image copyright"), max_length=40, blank=True, null=True
    )
    image_copyright_url = models.CharField(
        _("image copyright url"), max_length=150, blank=True, null=True
    )


class Roll(models.Model):
    campaign = models.ForeignKey(
        Campaign, blank=True, null=True, on_delete=models.CASCADE
    )
    character = models.ForeignKey(
        "characters.Character", blank=True, null=True, on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    header = models.CharField(_("header"), max_length=120, blank=True, null=True)
    description = models.TextField(_("description"), blank=True, null=True)
    roll_string = models.CharField(
        _("roll string"), max_length=20, blank=True, null=True
    )
    results_csv = models.CharField(_("results_csv"), max_length=120)

    modifier = models.IntegerField(_("modifier"), default=0)
    minimum_roll = models.IntegerField(_("minimum roll"), default=5)

    # statistics
    crit_count = models.IntegerField(_("crit count"), default=0)
    crit_sum = models.IntegerField(_("crit sum"), default=0)
    exploded_dice_count = models.IntegerField(_("exploded dice count"), default=0)
    exploded_dice_sum = models.IntegerField(_("exploded dice sum"), default=0)
    highest_single_roll = models.IntegerField(_("highest single roll"), default=0)
    successes_count = models.IntegerField(_("successes count"), default=0)
    successes_sum = models.IntegerField(_("successes sum"), default=0)
    fails_count = models.IntegerField(_("fails count"), default=0)
    fails_sum = models.IntegerField(_("fails sum"), default=0)
    total_sum = models.IntegerField(_("total sum"), default=0)

    class Meta:
        ordering = ("-created_at",)

    def save(self, *args, **kwargs):
        dice_list = [int(v) for v in self.results_csv.strip().split(",") if v]
        successes = [v for v in dice_list if v >= self.minimum_roll]
        fails = [v for v in dice_list if v < self.minimum_roll]
        exploded = [v for v in dice_list if v >= 6]
        crits = [v for v in dice_list if v >= 11]

        self.crit_count = len(crits)
        self.crit_sum = sum(crits)
        self.exploded_dice_count = len(exploded)
        self.exploded_dice_sum = sum(exploded)
        self.highest_single_roll = max(dice_list, default=0)
        self.successes_count = len(successes)
        self.successes_sum = sum(successes)
        self.fails_count = len(fails)
        self.fails_sum = sum(fails)
        self.total_sum = sum(dice_list) + self.modifier
        super().save(*args, **kwargs)

    def __str__(self):
        return self.header

    def get_sum(self):
        return sum(self.get_dice_list()) + self.modifier

    def get_dice_list(self):
        return [int(v) for v in self.results_csv.strip().split(",") if v]

homebrew/models.py
from django.db import models
from django.utils.translation import gettext_lazy as gt


class HomebrewQuerySet(models.QuerySet):
    def homebrew(self, character=None, campaign=None):
        qs = self.filter(is_homebrew=True)
        if campaign is not None:
            return qs.filter(homebrew_campaign=campaign)
        elif character is not None:
            return qs.filter(homebrew_character=character)
        return qs

    def without_homebrew(self):
        return self.filter(is_homebrew=False)


class HomebrewModel(models.Model):
    is_homebrew = models.BooleanField(gt('is homebrew'), default=False)
    keep_as_homebrew = models.BooleanField(
        gt('keep as homebrew'),
        help_text=gt('This was not accepted as general spell and is kept as homebrew.'),
        default=False)
    homebrew_campaign = models.ForeignKey(
        'campaigns.Campaign',
        related_name="homebrew_%(app_label)s_%(class)s_set",
        blank=True,
        null=True,
        verbose_name=gt('homebrew campaign'),
        on_delete=models.SET_NULL)
    homebrew_character = models.ForeignKey(
        'characters.Character',
        related_name="homebrew_%(app_label)s_%(class)s_set",
        blank=True,
        null=True,
        verbose_name=gt('homebrew character'),
        on_delete=models.SET_NULL)

    class Meta:
        abstract = True

campaigns/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from campaigns.models import Scene, Campaign
from rules.models import Extension


class CreateCampaignExtensionsForm(forms.Form):
    extensions = forms.ModelMultipleChoiceField(
        queryset=Extension.objects.filter(type__in=['x', 'w'], is_mandatory=False, is_active=True),
        label=_('Extensions'),
        required=False,
        widget=forms.SelectMultiple(attrs={'style': 'display: none'}))


class SettingsForm(forms.ModelForm):
    class Meta:
        model = Campaign
        fields = ('name', 'abstract',
                  'currency_map', 'seed_money', 'starting_template_points',
                  'character_visibility', 'foe_visibility',
                  'npc_visibility', 'game_log_visibility',
                  'discord_webhook_url', 'image', 'backdrop_image')


class SceneForm(forms.ModelForm):
    class Meta:
        model = Scene
        fields = ('name', 'text')

campaigns/templates/campaigns/fragments/campaign.html
{% extends 'campaigns/fragments/fragment_base.html' %}
{% load portal_extras %}
{% load i18n thumbnail static %}

{% block fragment %}
  {% if object.abstract %}
    <p>{{ object.abstract }}</p>
  {% endif %}

  {% if may_join %}
    <div class="card mb-4">
      <div class="card-body py-3">
        <div class="d-flex align-items-center justify-content-start gap-3">
          <i class="gi gi-cathelineau-swordwoman fs-1"></i>
          <div>
            {% trans "You have been invited to join this campaign. Create a new character to join the campaign." %}<br>
            <a href=""
               data-sidebar-title="{% trans 'Join campaign' %}"
               data-sidebar-url="{% url 'campaigns:xhr_sidebar' pk=object.id sidebar_template="join" %}"
               class="sidebar-trigger btn btn-success mt-2"><i
                    class="fas fa-dice-five"></i> {% trans 'Join campaign' %}</a>
          </div>
        </div>
        <br>
      </div>
    </div>
  {% endif %}


  <h2>{% trans "Players" %}</h2>
  <div class="campaign-characters">
    <div class="d-flex justify-content-start flex-wrap">
      {% for c in object.character_set.all %}
        <a href=""
           data-sidebar-title="{{ c }}"
           data-sidebar-url="{% url 'campaigns:xhr_character_sidebar' pk=c.id sidebar_template="character" %}"
           class="sidebar-trigger sidebar-spinner mb-2 me-2">
          <img src="{% image_url c geometry="200x200" crop="center" %}" alt="{{ c }}">
        </a>
      {% endfor %}

    {% if may_edit %}
      <a href="{{ object.invite_link }}" class="campaign-link" data-msg="{% trans "Invite link copied" %}">
        <div class="card d-flex justify-content-center align-items-center me-2 mb-2"
             style="width: 200px; height: 200px">
          <i class="fas fa-plus fa-2x"></i>
          <span class="invite-text">{% trans "Invite Player" %}</span>
        </div>
      </a>
    {% endif %}

    </div>
  </div>
{% endblock %}

campaigns/templates/campaigns/fragments/foes.html
{% extends 'campaigns/fragments/fragment_base.html' %}
{% load i18n rules_extras django_bootstrap5 characters_extras %}

{% block fragment %}
    <div class="table-responsive">
        <table class="table campaign-status-sortable">
            <thead>
            <tr class="pointer">
                <th>{% trans 'Foe' %}</th>
                <th>{% trans 'Wounds' %}</th>
                <th>{% trans 'Protection' %}</th>
                <th>{% trans 'Arcana' %}</th>
                <th>{% trans 'Actions' %}</th>
                <th>{% trans 'Perception' %}</th>
                <th>{% trans 'Walking Range' %}</th>
                <th>{% trans 'Minimum Roll' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for foe in object.foe_set.all %}
                {% with wiki_page=foe.wiki_page %}
                    {% with game_values=wiki_page.wikipagegamevalues_set.latest %}
                        <tr class="pointer sidebar-trigger" data-sidebar-title="{{ foe.wiki_page }}" data-sidebar-url="{% url 'campaigns:xhr_foe_sidebar' pk=foe.id sidebar_template="foe" %}">
                            <td>{{ wiki_page }} <small class="text-muted">{{ wiki_page.world }}</small></td>
                            <td>{% color_value_span game_values.health 6 %}</td>
                            <td>{% color_value_span game_values.protection 3 %}</td>
                            <td>{% color_value_span game_values.arcana 6 %}</td>
                            <td>{% color_value_span game_values.actions 3 %}</td>
                            <td>{% color_value_span game_values.perception 3 %}</td>
                            <td>{% color_value_span game_values.walking_range 5 %}</td>
                            <td>{% color_value_span game_values.minimum_roll 5 invert=True %}+</td>
                        </tr>
                    {% endwith %}
                {% endwith %}
            {% endfor %}
            </tbody>
        </table>
        {% if may_edit %}
            <a
                href=""
                data-sidebar-url="{% url 'campaigns:xhr_search_foe' pk=object.id %}"
                data-sidebar-title="{% trans "Search foe" %}"
                class="btn btn-primary float-end sidebar-trigger">{% trans 'Add foe' %}</a>
        {% endif %}
    </div>
{% endblock %}

campaigns/templates/campaigns/fragments/fragment_base.html
<div class="fragment" data-fragment-url="{% url 'campaigns:xhr_campaign_fragment' pk=object.id fragment_template=fragment_template %}">
    {% block fragment %}{% endblock %}
</div>

campaigns/templates/campaigns/fragments/homebrew.html
{% load i18n thumbnail static armory_extras rules_extras %}

{% block fragment %}
  <div class="column-container column-layout-3">

    {% if may_edit %}
      <div class="pb-3">
        <div class="card pointer" data-bs-toggle="dropdown">
          <div class="card-body d-flex flex-column align-items-center justify-content-center">
            <i class="fas fa-plus fa-2x"></i><br>
            <div class="dropdown mt-2">
              <button class="btn" type="button" data-bs-toggle="dropdown"
                      aria-expanded="false">
                {% trans "Create custom" %}
              </button>
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item modal-trigger"
                     data-url="{% url 'homebrew:xhr_create_item' %}?campaign_pk={{ object.id }}"
                     data-bs-toggle="modal"
                     data-bs-target=".page-modal"
                     data-modal-title="{% trans 'Create Item' %}"
                     href="">{% trans "Create custom item" %}</a>
                </li>
                <li>
                  <a data-url="{% url 'homebrew:xhr_create_weapon' %}?campaign_pk={{ object.id }}"
                     data-bs-toggle="modal"
                     data-bs-target=".page-modal"
                     data-modal-title="{% trans 'Create Weapon' %}"
                     class="dropdown-item modal-trigger" href="#">{% trans "Create custom weapon" %}</a>
                </li>
                <li>
                  <a data-url="{% url 'homebrew:xhr_create_riot_gear' %}?campaign_pk={{ object.id }}"
                     data-bs-toggle="modal"
                     data-bs-target=".page-modal"
                     data-modal-title="{% trans 'Create Armour' %}"
                     class="dropdown-item modal-trigger" href="#">{% trans "Create custom armour" %}</a>
                </li>
                <li>
                  <a data-url="{% url 'homebrew:xhr_create_base_spell' %}?campaign_pk={{ object.id }}"
                     data-bs-toggle="modal"
                     data-bs-target=".page-modal"
                     data-modal-title="{% trans 'Create Spell' %}"
                     class="dropdown-item modal-trigger" href="#">{% trans "Create custom spell" %}</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    {% endif %}

    {% for item in object.homebrew_armory_item_set.all %}
      {% item_widget item %}
    {% endfor %}
    {% for weapon in object.homebrew_armory_weapon_set.all %}
      {% weapon_widget weapon %}
    {% endfor %}
    {% for riot_gear in object.homebrew_armory_riot_gear_set.all %}
      {% riot_gear_widget riot_gear %}
    {% endfor %}
    {% for spell in object.homebrew_magic_basespell_set.all %}
      {% basespell_widget spell %}
    {% endfor %}
  </div>
{% endblock %}

campaigns/templates/campaigns/fragments/settings.html
{% extends 'campaigns/fragments/fragment_base.html' %}
{% load i18n thumbnail static characters_extras campaign_extras %}

{% block fragment %}
    <div class="row">
        <div class="col-12">
            {% trans 'World' %}
            <span class="float-end">{{ object.world }}</span>
            <hr>

            {% trans 'Epoch' %}
            <span class="float-end">{{ object.epoch }}</span>
            <hr>

            {% trans 'Extensions' %}
            <span class="float-end">{{ object.extension_string }}</span>
            <hr>

            {% trans 'Currency Map' %}
            <span class="float-end">{{ object.currency_map }}</span>
            <hr>

            {% trans 'Seed Money' %}
            <span class="float-end">{{ object.seed_money }}</span>
            <hr>

            {% trans 'Additional starting career points' %}
            <span class="float-end">{{ object.starting_template_points }}</span>
            <hr>

            {% trans 'Character Visibility' %}
            <span class="float-end">{{ object.get_character_visibility_display }}</span>
            <hr>

            {% trans 'NPC Visibility' %}
            <span class="float-end">{{ object.get_npc_visibility_display }}</span>
            <hr>

            {% trans 'Foe Visibility' %}
            <span class="float-end">{{ object.get_foe_visibility_display }}</span>
            <hr>

            {% trans 'Game Log Visibility' %}
            <span class="float-end">{{ object.get_game_log_visibility_display }}</span>
            <hr>

            {% trans 'Discord Dice Rolls' %}
            <span class="float-end">{% if object.discord_webhook_url %}{% trans 'Yes' %}{% else %}{% trans 'No' %}{% endif %}</span>
            <hr>

            {% if may_edit %}
                <a href=""
                   data-sidebar-title="{% trans 'Edit settings' %}"
                   data-sidebar-url="{% url 'campaigns:xhr_settings_sidebar' pk=object.id sidebar_template='settings' %}"
                   class="btn btn-primary sidebar-trigger">{% trans 'Edit settings' %}</a>
            {% endif %}
        </div>

    </div>
{% endblock %}