characters/urls.py
from django.urls import path

from characters import views

app_name = "characters"

urlpatterns = [
    path("detail/<int:pk>", views.CharacterDetailView.as_view(), name="detail"),
    path("pdf/<int:pk>", views.CharacterPDFView.as_view(), name="pdf"),
    path(
        "xhr_delete/<int:pk>", views.XhrDeleteCharacterView.as_view(), name="xhr_delete"
    ),
    path("dice_log/<int:pk>", views.XhrDiceLogView.as_view(), name="xhr_dice_log"),
    # Sidebars and Fragments
    path(
        r"sidebar/<int:pk>/<str:sidebar_template>/",
        views.XhrSidebarView.as_view(),
        name="xhr_sidebar",
    ),
    path(
        r"sidebar/<int:pk>/<str:sidebar_template>/knowledge/<int:knowledge_pk>/",
        views.XhrSidebarView.as_view(),
        name="xhr_sidebar_knowledge",
    ),
    path(
        r"sidebar/<int:pk>/<str:sidebar_template>/action/<int:priest_action_pk>/",
        views.XhrSidebarView.as_view(),
        name="xhr_sidebar_priest_action",
    ),
    path(
        "xhr_detail_fragment/<int:pk>/<fragment_template>",
        views.XhrDetailFragmentView.as_view(),
        name="xhr_detail_fragment",
    ),
    # attributes
    path(
        "attribute/<int:character_attribute_pk>/<mode>/",
        views.CharacterModifyAttributeView.as_view(),
        name="modify_attribute",
    ),
    # health and protection
    path(
        "health/<int:pk>/<mode>/",
        views.CharacterModifyHealthView.as_view(),
        name="modify_health",
    ),
    path(
        "protection/<int:pk>/<protection_type_pk>/<riot_gear_pk>/spend",
        views.CharacterSpendProtectionView.as_view(),
        name="spend_protection",
    ),
    path(
        "protection/<int:pk>/restore",
        views.CharacterRestoreAllProtectionView.as_view(),
        name="restore_protection",
    ),
    path("rest/<int:pk>/", views.XhrCharacterRestView.as_view(), name="xhr_rest"),
    # magic
    path(
        "arcana/<int:pk>/<mode>/",
        views.CharacterModifyArcanaView.as_view(),
        name="modify_arcana",
    ),
    path(
        "spell/cast/<int:pk>/",
        views.CharacterCastSpellView.as_view(),
        name="cast_spell",
    ),
    path(
        "xhr_add_spell_template/<int:pk>",
        views.XhrAddSpellTemplateView.as_view(),
        name="xhr_add_spell_template",
    ),
    path(
        "add_spell_template/<int:pk>/<int:spell_template_pk>/<int:character_spell_pk>",
        views.AddSpellTemplateView.as_view(),
        name="add_spell_template",
    ),
    # pantheon
    path(
        "grace/<int:pk>/<mode>/",
        views.CharacterModifyGraceView.as_view(),
        name="modify_grace",
    ),
    path(
        "attitude/<int:pk>/<mode>/",
        views.CharacterModifyAttitudeView.as_view(),
        name="modify_attitude",
    ),
    # dice
    path(
        "dice/<int:pk>/<mode>/",
        views.CharacterModifyDiceView.as_view(),
        name="modify_dice",
    ),
    # Weapons
    path(
        "attack/<int:characterweapon_pk>/<int:attack_mode_pk>/",
        views.CharacterAttackView.as_view(),
        name="attack",
    ),
    path(
        "reload/<int:characterweapon_pk>/",
        views.CharacterReloadView.as_view(),
        name="reload",
    ),
    # horror
    path(
        "stress/<int:pk>/<mode>/",
        views.CharacterModifyStressView.as_view(),
        name="modify_stress",
    ),
    # new character
    path("new/", views.CreateCharacterView.as_view(), name="create_character"),
    path(
        "new/<int:world_pk>/",
        views.CreateCharacterEpochView.as_view(),
        name="create_character_epoch",
    ),
    path(
        "new/<int:world_pk>/<int:epoch_pk>/",
        views.CreateCharacterExtensionsView.as_view(),
        name="create_character_extensions",
    ),
    path(
        "new/data/<int:world_pk>/<int:epoch_pk>/",
        views.CreateCharacterDataView.as_view(),
        name="create_character_data",
    ),
    path(
        "new/info/<int:world_pk>/<int:epoch_pk>/",
        views.CreateCharacterInfoView.as_view(),
        name="create_character_info",
    ),
    path(
        "new/data/<int:epoch_pk>/<int:world_pk>/<int:campaign_pk>/<hash>/<type>/",
        views.CreateCharacterDataView.as_view(),
        name="create_character_data",
    ),
    path(
        "new/random_npc/<int:epoch_pk>/<int:world_pk>/<int:campaign_pk>/<hash>/<type>/",
        views.CreateRandomNPCView.as_view(),
        name="create_random_npc",
    ),
    # constructed
    path(
        "new/constructed/<int:pk>",
        views.CreateCharacterConstructedView.as_view(),
        name="create_character_constructed",
    ),
    path(
        "new/constructed/add_template/<int:pk>",
        views.XhrConstructedAddTemplateView.as_view(),
        name="xhr_constructed_add_template",
    ),
    path(
        "new/constructed/preview/<int:pk>",
        views.XhrCreateCharacterPreviewView.as_view(),
        name="xhr_create_character_preview",
    ),
    path(
        "new/constructed/remove_template/<int:pk>",
        views.XhrConstructedRemoveTemplateView.as_view(),
        name="xhr_constructed_remove_template",
    ),
    # Images etc
    path("change_image/<int:pk>", views.ChangeImageView.as_view(), name="change_image"),
    # reputation and status
    path(
        "xhr_reputation/<int:pk>",
        views.XhrCharacterModifyReputationView.as_view(),
        name="xhr_modify_reputation",
    ),
    path(
        "xhr_status_effects/change/<int:pk>/<int:status_effect_pk>/<mode>/",
        views.XhrCharacterStatusEffectsChangeView.as_view(),
        name="xhr_status_effects_change",
    ),
    # generic add and remove
    path(
        "xhr_character_objects/<int:pk>/<str:object_type>",
        views.XhrCharacterObjectsView.as_view(),
        name="xhr_character_objects",
    ),
    # weapons
    path(
        "xhr_remove_weapon_modification/<int:pk>/<int:weapon_pk>/<int:weapon_modification_pk>",
        views.XhrRemoveWeaponModificationView.as_view(),
        name="xhr_remove_weapon_modification",
    ),
    path(
        "xhr_weapon_condition/<int:pk>/<int:weapon_pk>/<mode>/",
        views.XhrWeaponConditionView.as_view(),
        name="xhr_weapon_condition",
    ),
    # riot gear
    path(
        "xhr_riot_gear_condition/<int:pk>/<int:riot_gear_pk><mode>/",
        views.XhrRiotGearConditionView.as_view(),
        name="xhr_riot_gear_condition",
    ),
    # items
    path(
        "xhr_modify_item/<int:pk>/<int:item_pk>/<mode>",
        views.XhrModifyItemView.as_view(),
        name="xhr_modify_item",
    ),
    path(
        "xhr_update_item_sort_order/<int:pk>",
        views.XhrUpdateItemSortOrderView.as_view(),
        name="xhr_update_item_sort_order",
    ),
    path(
        "modify_currency/<int:pk>",
        views.XhrModifyCurrencyView.as_view(),
        name="xhr_modify_currency",
    ),
    path(
        "xhr_put_into/<int:pk>/<int:item_pk>/<int:container_pk>",
        views.XhrPutIntoView.as_view(),
        name="xhr_put_into",
    ),
    path(
        "xhr_put_into/<int:pk>/<int:item_pk>",
        views.XhrPutIntoView.as_view(),
        name="xhr_put_into",
    ),
    # weapon modifications
    path(
        "xhr_add_weapon_modifications/<int:pk>",
        views.XhrAddWeaponModView.as_view(),
        name="xhr_add_weapon_modifications",
    ),
    path(
        "add_weapon_modification/<int:pk>/<int:weapon_modification_pk>/<int:character_weapon_pk>",
        views.AddWeaponModificationView.as_view(),
        name="add_weapon_modification",
    ),
    # Notes
    path(
        "xhr_create_note/<int:pk>",
        views.XhrCreateNoteView.as_view(),
        name="xhr_create_note",
    ),
    path(
        "xhr_update_note/<int:pk>/<int:note_pk>",
        views.XhrUpdateNoteView.as_view(),
        name="xhr_update_note",
    ),
    path(
        "xhr_delete_note/<int:pk>/<int:note_pk>",
        views.XhrDeleteNoteView.as_view(),
        name="xhr_delete_note",
    ),
]

urpg/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.views.static import serve
from django_registration.backends.activation.views import RegistrationView

from characters.feeds import LatestModifiedAdmin, LatestNewAdmin
from portal.forms import CustomRegistrationForm
from portal.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("feeds/new_admin/", LatestNewAdmin()),
    path("feeds/modified_admin/", LatestModifiedAdmin()),
    path("", include("characters.urls", namespace="characters")),
    path("admin/", admin.site.urls),
    path(
        "contact/", TemplateView.as_view(template_name="contact.html"), name="contact"
    ),
    path("campaigns/", include("campaigns.urls", namespace="campaigns")),
    path("magic/", include("magic.urls", namespace="magic")),
    path("forum/", include("forum.urls", namespace="forum")),
    path("rulebook/", include("rulebook.urls", namespace="rulebook")),
    path("homebrew/", include("homebrew.urls", namespace="homebrew")),
    path("rules/", include("rules.urls", namespace="rules")),
    path("armory/", include("armory.urls", namespace="armory")),
    path("world/", include("worlds.urls", namespace="world")),
    path("gmtools/", include("gmtools.urls", namespace="gmtools")),
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        "accounts/register/",
        RegistrationView.as_view(form_class=CustomRegistrationForm),
        name="django_registration_register",
    ),
    path("accounts/", include("django_registration.backends.activation.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("portal/", include("portal.urls", namespace="portal")),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT})
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    if settings.DEBUG_TOOLBAR:
        urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

characters/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from armory.models import CurrencyMap
from characters.models import Character
from pantheon.models import Entity
from rules.models import Lineage, Extension


class CharacterImageForm(forms.ModelForm):
    class Meta:
        model = Character
        fields = ("name", "description", "image", "backdrop_image")


class CreateCharacterExtensionsForm(forms.Form):
    extensions = forms.ModelMultipleChoiceField(
        queryset=Extension.objects.filter(
            type__in=["x", "w"], is_mandatory=False, is_active=True
        ),
        label=_("Extensions"),
        required=False,
        widget=forms.SelectMultiple(attrs={"style": "display: none"}),
    )


class CreateCharacterDataForm(forms.Form):
    name = forms.CharField(label=_("Name"), max_length=80)
    lineage = forms.ModelChoiceField(
        queryset=Lineage.objects.all(), empty_label=None, label=_("Lineage")
    )
    currency_map = forms.ModelChoiceField(
        queryset=CurrencyMap.objects.all(),
        required=True,
        empty_label=None,
        label=_("Currency Map"),
    )
    seed_money = forms.IntegerField(
        label=_("Seed Money"), min_value=0, max_value=100000, initial=2000
    )
    epoch = forms.ModelChoiceField(
        queryset=Extension.objects.filter(type="e", is_mandatory=False, is_active=True),
        label=_("Epoch"),
        widget=forms.HiddenInput(),
    )
    world = forms.ModelChoiceField(
        queryset=Extension.objects.filter(type="w", is_mandatory=False, is_active=True),
        label=_("Epoch"),
        widget=forms.HiddenInput(),
    )
    extensions = forms.ModelMultipleChoiceField(
        queryset=Extension.objects.filter(
            type__in=["x"], is_mandatory=False, is_active=True
        ),
        label=_("Extensions"),
        required=False,
        widget=forms.SelectMultiple(attrs={"style": "display: none"}),
    )
    size = forms.IntegerField(label=_("Size"), required=False)
    weight = forms.IntegerField(label=_("Weight"), required=False)
    date_of_birth = forms.CharField(label=_("Date of birth"), required=False)
    entity = forms.ModelChoiceField(
        queryset=Entity.objects.all(),
        required=False,
        empty_label=_("None"),
        label=_("Entity"),
    )
    attitude = forms.IntegerField(label=_("Attitude"), required=True, initial=50)


class CreateRandomNPCForm(CreateCharacterDataForm):
    starting_reputation = forms.IntegerField(label=_("Starting Reputation"), initial=50)
    attitude = forms.IntegerField(
        label=_("Attitude"), required=True, initial=50, widget=forms.HiddenInput()
    )

characters/templates/characters/_character_list_widget.html
{% load portal_extras %}
{% load i18n static thumbnail characters_extras %}

<a class="character-list-widget" href="{{ character.get_absolute_url }}" data-character-id="{{ character.id }}">
  <div class="card character-list-item h-100">
    <img src="{% backdrop_image_url character %}" alt="{{ character }}" class="card-img-top object-fit-cover"
         style="height:120px;">
    <div class="d-flex align-items-center hover-pointer"
         style="position:absolute; left:32px; top:32px">
      <img class="img-fluid rounded float-start me-3 border-3 border-black"
           src="{% image_url character "120x120" %}"
           alt="{{ character.name }}">
    </div>
    <div class="card-body mt-5">
      <h4>{{ character.name }}</h4>
      {% template_category_string character 3 %}
      {% if character.created_by != request.user %}
        <small>{{ character.created_by|default:"" }}</small>
      {% endif %}
    </div>
  </div>
</a>

characters/templates/characters/character_detail.html
{% extends 'base.html' %}
{% load portal_extras %}
{% load i18n rules_extras characters_extras campaign_extras thumbnail static %}

{% block title %}{{ object }} - {{ block.super }}{% endblock %}
{% block in_page_title %}{{ object }}{% endblock %}
{% block in_page_subtitle %}
  {{ object.lineage }} - {% template_category_string object 3 %}
  {% if object.pc_or_npc_campaign %}
    <a href="{% url 'campaigns:detail' pk=object.pc_or_npc_campaign.id %}">{{ object.pc_or_npc_campaign }}</a>
  {% endif %}
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/character_detail.js' %}"></script>
  <script src="{% static 'js/campaign_socket.js' %}"></script>
  <script>
      $(function () {
          $('.character-main-nav a[href]:first').tab('show')
      })
  </script>
{% endblock %}

{% block bottom_nav %}
  {% bottom_navigation_button "characters/_navigation.html" %}
{% endblock %}

{% block content %}
  <div id="dice-log-toggle"
       hx-get="{% url 'characters:xhr_dice_log' pk=object.id %}"
       hx-target="#dice-log-entries"
       onclick="toggleDiceLog()">
    <i class="gi gi-delapouite-dice-six-faces-five me-2"></i>
    {% trans "Dice Log" %}
  </div>

  <div id="dice-log">
    <div id="dice-log-entries"></div>
  </div>

  <div class="d-none" id="room-url">{% ws_room_url object.ws_room_name %}</div>
  <audio class="d-none" id="room-audio" src="{% static 'roll.mp3' %}"></audio>

  <div class="row">
    <div class="col-12 col-xl-3 d-none d-xl-block">
      {% include 'characters/_navigation.html' with object=object may_edit=may_edit %}
    </div>

    <div class="col-12 col-xl-9">

      {% if not object.created_by %}
        <div class="alert alert-danger" role="alert">
          {% trans 'This character was created while not being logged in. It will be deleted by tomorrow.' %}
        </div>
      {% endif %}

      {% detail_fragment "status" %}

      <div class="tab-content">
        <div class="tab-pane fade show active" id="v-description" role="tabpanel">
          {% detail_fragment 'description' %}
        </div>

        <div class="tab-pane fade" id="v-character" role="tabpanel">
          {% detail_fragment 'character' %}
        </div>

        <div class="tab-pane fade" id="v-gear" role="tabpanel">
          {% detail_fragment 'gear' %}
        </div>

        <div class="tab-pane fade" id="v-combat" role="tabpanel">
          {% detail_fragment 'combat' %}
        </div>

        <div class="tab-pane fade" id="v-magic" role="tabpanel">
          {% detail_fragment 'magic' %}
        </div>

        <div class="tab-pane fade" id="v-pantheon" role="tabpanel">
          {% detail_fragment 'pantheon' %}
        </div>

        <div class="tab-pane fade" id="v-horror" role="tabpanel">
          {% detail_fragment 'horror' %}
        </div>

        <div class="tab-pane fade" id="v-background" role="tabpanel">
          {% detail_fragment 'advancement' %}
        </div>

        <div class="tab-pane fade" id="v-notes" role="tabpanel">
          {% detail_fragment 'notes' %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

characters/templates/characters/create_character.html
{% extends 'base.html' %}
{% load i18n thumbnail %}

{% block title %}{% trans 'Create Character' %} - {{ block.super }}{% endblock %}
{% block in_page_title %}{% trans "Create Character" %}{% endblock %}
{% block in_page_subtitle %}{% trans "Choose a world to play in" %}{% endblock %}

{% block content %}
  <div class="row">
    {% for extension in extensions %}
      <div class="col-12 col-md-6 col-lg-4">
        {% if extension.fixed_epoch %}
          {% if extension.fixed_extensions.exists %}
            <a href="{% url 'characters:create_character_data' world_pk=extension.id epoch_pk=extension.fixed_epoch.id %}">
          {% else %}
            <a href="{% url 'characters:create_character_extensions' world_pk=extension.id epoch_pk=extension.fixed_epoch.id %}">
          {% endif %}
        {% else %}
          <a href="{% url 'characters:create_character_epoch' world_pk=extension.id %}">
        {% endif %}
        <div class="card text-center create-epoch-card mb-4">
          {% thumbnail extension.image "1024" as im %}
            <div class="card-body" style="background-image: url({{ im.url }}); background-size: cover">
          {% endthumbnail %}
          <div class="card-text w-100 p-5">
            <h5 class="text-center p-0 m-0">{{ extension }}</h5>
            <p class="text-center text-gray p-0 m-0">{{ extension.year_range }}</p>
          </div>
          </div>
        </div>
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock %}

characters/templates/characters/create_character_constructed.html
{% extends 'base.html' %}
{% load i18n rules_extras characters_extras %}

{% block title %}{% trans 'Create Character' %} - {{ block.super }}{% endblock %}
{% block in_page_title %}{% trans "Select templates" %}{% endblock %}
{% block in_page_subtitle %}
  {% trans 'These are the templates your character will start with. They define all values and abilities of your character.' %}{% endblock %}

{% block javascript %}
  <script>
      $(function () {
          let timer = null;

          function displayWarnings(warnings) {
              let element = $('.character-warnings');
              element.html("");
              if (!!warnings.length) {
                  element.removeClass('d-none');
                  for (let warning of warnings) {
                      element.append(`<div>${warning}</div>`)
                  }
              } else {
                  element.addClass("d-none");
              }
          }

          $('#id_q').on('keyup', function (e) {
              let q = $(this).val();

              function updateTabs() {
                  $('.tab-pane').each(function (index) {
                      let elem = $(this);
                      let ct = elem.find('.constructed-template:not(.d-none)');
                      if (ct.length === 0) {
                          elem.addClass('d-none');
                          $(elem.data('rel')).addClass('disabled');
                      } else {
                          elem.removeClass('d-none');
                          $(elem.data('rel')).removeClass('disabled');
                      }
                      $('a[data-bs-toggle="tab"]:not(.disabled):first').tab('show');
                  })
              }

              if (timer) {
                  clearTimeout(timer);
              }
              timer = setTimeout(function () {
                  $('.constructed-template').each(function (index) {
                      if ($(this).text().toLowerCase().search(q.toLowerCase()) > -1) {
                          $(this).removeClass('d-none');
                      } else {
                          $(this).addClass('d-none');
                      }
                  });
                  updateTabs();
              }, 100);
          });

          $('.row').on('click', '.constructed-template', function (e) {
              let template_div = $(this);
              let template_id = template_div.data('template-id');
              let preview_url = template_div.data('preview-url');
              if (template_div.hasClass('selected')) {
                  $.post(
                      template_div.data('remove-url'),
                      {template_id: template_id},
                      function (data) {
                          if (data.status === 'ok') {
                              $('.template-points').text(data.remaining_points);
                              template_div.removeClass('selected');
                              displayWarnings(data.warnings);
                              $('.character-preview').load(preview_url);
                          } else {
                              // shake
                          }
                      });
              } else {
                  $.post(
                      template_div.data('add-url'),
                      {template_id: template_id},
                      function (data) {
                          if (data.status === 'ok') {
                              $('.template-points').text(data.remaining_points);
                              template_div.addClass('selected');
                              displayWarnings(data.warnings);
                              $('.character-preview').load(preview_url);
                          } else {
                              template_div.addClass('notenoughpoints');
                              $('.template-points').addClass('animated wobble');
                              setTimeout(function () {
                                  template_div.removeClass('notenoughpoints');
                                  $('.template-points').removeClass('animated wobble');
                              }, 500);
                          }
                      });
              }
              e.preventDefault();
              return false;
          });

          $('#switch-preview').on('change', function () {
              if ($(this).prop('checked')) {
                  $('.template-list').addClass('d-none');
                  $('.character-preview').removeClass('d-none');
              } else {
                  $('.character-preview').addClass('d-none');
                  $('.template-list').removeClass('d-none');
              }
          });
      })
  </script>
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-12 col-md-3">
      <div class="row initial-data">
        <div class="col-md-12">
          <input type="text" class="form-control mb-3 w-100" placeholder="{% trans "Search" %}" id="id_q">
          <div class="h2">
            <span class="badge bg-info template-points">{{ character.remaining_template_points }}</span>
          </div>
          <h4>{% trans "Character Points" %}</h4>

          <p class="text-muted">{% trans 'Excess points will become the new characters initial reputation.' %}</p>
          <form action="{% url 'characters:create_character_constructed' pk=character.id %}" method="post">
            {% csrf_token %}
            <div class="alert alert-danger character-warnings {% if not warnings %}d-none{% endif %}">
              {% for warning in warnings %}
                <div>{{ warning }}</div>
              {% endfor %}
            </div>
            <button type="submit" class="btn mb-3 w-100 btn-success">{% trans 'Finish Character' %}</button>
            <br>
            <span class="switch switch-sm">
              <input type="checkbox" class="mt-3 switch" id="switch-preview">
              <label for="switch-preview">{% trans "Preview" %}</label>
            </span>
          </form>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-8 template-list">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-tabs nav-fill mb-2" role="tablist">
            {% for tc in template_categories %}
              <li class="nav-item">
                <a class="nav-link {% if forloop.first %}active{% endif %}" data-bs-toggle="tab"
                   href="#tc{{ tc.id }}" id="tab{{ tc.id }}">
                  {{ tc }}
                </a>
              </li>
            {% endfor %}
          </ul>
        </div>

        <div class="col-md-12 tab-content">
          {% for tc in template_categories %}
            <div class="tab-pane fade {% if forloop.first %}show active{% endif %}" id="tc{{ tc.id }}"
                 data-rel="#tab{{ tc.id }}">
              <div class="column-container column-layout-2">
                {% for i in tc.template_set.all %}
                  {% has_extensions i object.extensions.all as has_extension %}
                  {% if has_extension %}
                    <div class="constructed-template {% if i.id in character_template_ids %}selected{% endif %}"
                         data-template-id="{{ i.id }}"
                         data-add-url="{% url 'characters:xhr_constructed_add_template' pk=object.id %}"
                         data-remove-url="{% url 'characters:xhr_constructed_remove_template' pk=object.id %}"
                         data-preview-url="{% url 'characters:xhr_create_character_preview' pk=object.id %}">
                      {% template_widget i %}
                    </div>
                  {% endif %}
                {% endfor %}
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>

    <div class="col-12 col-md-9 character-preview d-none">
      {% detail_fragment 'character' %}
    </div>
  </div>

{% endblock %}

characters/templates/characters/create_character_epoch.html
{% extends 'base.html' %}
{% load i18n thumbnail %}

{% block title %}{% trans 'Create Character' %} - {{ block.super }}{% endblock %}
{% block in_page_title %}{% trans "Choose an epoch" %}{% endblock %}
{% block in_page_subtitle %}
  {% trans "Choose an epoch to play in. The chosen epoch determines which weapons, armour and items are available." %}{% endblock %}

{% block content %}
  <div class="row">
    {% for extension in extensions %}
      <div class="col-12 col-md-6 col-lg-4">
        <a href="{% url 'characters:create_character_extensions' world_pk=world_pk epoch_pk=extension.id %}">
          <div class="card text-center create-epoch-card mb-4">
            {% thumbnail extension.image "1024" as im %}
              <div class="card-body" style="background-image: url({{ im.url }}); background-size: cover">
            {% endthumbnail %}
            <div class="card-text w-100 p-5">
              <h5 class="text-center p-0 m-0">{{ extension }}</h5>
              <p class="text-center text-gray p-0 m-0">{{ extension.year_range }}</p>
            </div>
            </div>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock %}

characters/templates/characters/create_character_extensions.html
{% extends 'base.html' %}
{% load i18n thumbnail django_bootstrap5 %}

{% block title %}{% trans 'Create Character' %} - {{ block.super }}{% endblock %}
{% block in_page_title %}{% trans "Choose extensions" %}{% endblock %}
{% block in_page_subtitle %}{% trans "Choose any number of additional extensions to add to your character." %}{% endblock %}

{% block javascript %}
    <script>
        $(() => {
            $('.create-epoch-card').on('click', function () {
                let id = $(this).data('extension-id')
                let option = $(`#id_extensions>option[value=${id}]`)
                let was_selected = $(this).hasClass('selected')
                if (was_selected) {
                    option.removeAttr('selected')
                    $(this).removeClass('selected')
                } else {
                    option.attr('selected', 'selected')
                    $(this).addClass('selected')
                }
            })
        })
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        {% for extension in extensions %}
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card text-center create-epoch-card mb-4 pointer"
                         data-extension-id="{{ extension.id }}">
                        {% thumbnail extension.image "1024" as im %}
                            <div class="card-body"
                                style="background-image: url({{ im.url }}); background-size: cover">
                        {% endthumbnail %}
                            <div class="card-text w-100 p-5">
                                <h5 class="text-center p-0 m-0">{{ extension }}</h5>
                                <p class="text-center p-0 m-0">{{ extension.year_range }}</p>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}

        <form action="{% url 'characters:create_character_data' epoch_pk=epoch_pk world_pk=world_pk %}" method="get">
            {% bootstrap_field form.extensions show_label=False %}
            <button type="submit" class="btn btn-primary btn-block mt-2">{% trans 'Choose Extensions' %}</button>
        </form>
    </div>
{% endblock %}

characters/templates/characters/dice_log.html
{% load rules_extras %}
{% load i18n %}
{% for roll in page_obj %}
  {% trans 'GM' as character_default %}
  {{ roll.character|default:character_default }} - {{ roll.header }}
  {% include "campaigns/_dice_socket_results.html" with roll=roll %}
  <hr>
{% endfor %}