armory/urls.py
from django.urls import path

from armory import views

app_name = "armory"

urlpatterns = [
    path("marterial/", views.MaterialOverviewView.as_view(), name="material_overview"),
    path("weapons/", views.WeaponListView.as_view(), name="weapon_list"),
    path("riot_gear/", views.RiotGearListView.as_view(), name="riot_gear_list"),
    path("items/", views.ItemListView.as_view(), name="item_list"),
    path("items/<int:pk>/", views.ItemDetailView.as_view(), name="item_detail"),
]

rules/urls.py
from django.urls import path

from rules import views

app_name = 'rules'

urlpatterns = [
    path('templates/', views.TemplateListView.as_view(), name='template_list'),
]

urpg/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.views.static import serve
from django_registration.backends.activation.views import RegistrationView

from characters.feeds import LatestModifiedAdmin, LatestNewAdmin
from portal.forms import CustomRegistrationForm
from portal.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("feeds/new_admin/", LatestNewAdmin()),
    path("feeds/modified_admin/", LatestModifiedAdmin()),
    path("", include("characters.urls", namespace="characters")),
    path("admin/", admin.site.urls),
    path(
        "contact/", TemplateView.as_view(template_name="contact.html"), name="contact"
    ),
    path("campaigns/", include("campaigns.urls", namespace="campaigns")),
    path("magic/", include("magic.urls", namespace="magic")),
    path("forum/", include("forum.urls", namespace="forum")),
    path("rulebook/", include("rulebook.urls", namespace="rulebook")),
    path("homebrew/", include("homebrew.urls", namespace="homebrew")),
    path("rules/", include("rules.urls", namespace="rules")),
    path("armory/", include("armory.urls", namespace="armory")),
    path("world/", include("worlds.urls", namespace="world")),
    path("gmtools/", include("gmtools.urls", namespace="gmtools")),
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        "accounts/register/",
        RegistrationView.as_view(form_class=CustomRegistrationForm),
        name="django_registration_register",
    ),
    path("accounts/", include("django_registration.backends.activation.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("portal/", include("portal.urls", namespace="portal")),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT})
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    if settings.DEBUG_TOOLBAR:
        urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

worlds/urls.py
from django.urls import path

from worlds import views

app_name = "worlds"

urlpatterns = [
    path(
        "foe_list",
        views.WikiPageWithGameValuesView.as_view(),
        name="wiki_page_with_game_values",
    ),
    path("", views.WorldListView.as_view(), name="list"),
    path("<str:slug>", views.WorldDetailView.as_view(), name="detail"),
    path(
        "<str:world_slug>/<str:slug>",
        views.WikiPageDetailView.as_view(),
        name="wiki_page",
    ),
    path(
        "<str:world_slug>/<str:slug>/edit",
        views.WikiPageEditTextView.as_view(),
        name="edit_text",
    ),
    path(
        "xhr_create/page/<int:world_pk>",
        views.XhrCreateWikiPageView.as_view(),
        name="xhr_create_wiki_page",
    ),
    path(
        "xhr_create/page/<int:world_pk>/<int:parent_pk>",
        views.XhrCreateWikiPageView.as_view(),
        name="xhr_create_wiki_page",
    ),
    # Sidebars
    path(
        r"sidebar/<str:slug>/<str:sidebar_template>/",
        views.XhrSidebarView.as_view(),
        name="xhr_sidebar",
    ),
    path(
        r"world_sidebar/<str:slug>/<str:sidebar_template>",
        views.XhrWorldSortSubPagesSidebarView.as_view(),
        name="xhr_world_sort_sidebar",
    ),
    path(
        r"wikipage_sidebar/<str:slug>/<str:sidebar_template>",
        views.XhrWikiPageSortSubPagesSidebarView.as_view(),
        name="xhr_wiki_page_sort_sidebar",
    ),
    path(
        "xhr_update_wiki_page_sort_order/<int:pk>/<str:model>",
        views.XhrUpdateItemSortOrderView.as_view(),
        name="xhr_update_wiki_page_sort_order",
    ),
    path(
        r"search_links/<str:world_slug>/",
        views.XhrSearchLinksView.as_view(),
        name="xhr_search_links",
    ),
    path(
        r"upload_image/<str:slug>/<str:kind>",
        views.XhrUploadImageView.as_view(),
        name="xhr_upload_image",
    ),
    path(
        r"additional_images/<str:slug>/",
        views.XhrAdditionalImagesView.as_view(),
        name="xhr_additional_images",
    ),
    path(
        r"xhr_auto_tag/<int:pk>/", views.XhrAutoTagView.as_view(), name="xhr_auto_tag"
    ),
]

armory/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _
from transmeta import TransMeta

from armory.choices import (
    COLOR_CLASS_CHOICES,
    PROTECTION_FA_ICON_CLASS_CHOICES,
    CURRENCY_FA_ICON_CLASS_CHOICES,
)
from armory.mixins import SearchableCardListMixin
from homebrew.models import HomebrewModel, HomebrewQuerySet
from rules.models import ExtensionSelectQuerySet, Extension


class ItemTypeQuerySet(models.QuerySet):
    def for_extensions(self, extension_rm):
        return self.filter(
            Q(item__extensions__id__in=extension_rm.all())
            | Q(item__extensions__id__in=Extension.objects.filter(is_mandatory=True))
        ).distinct()


class ItemType(SearchableCardListMixin, models.Model, metaclass=TransMeta):
    objects = ItemTypeQuerySet.as_manager()

    name = models.CharField(_("name"), max_length=100)
    description = models.TextField(_("description"), blank=True, null=True)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    modified_at = models.DateTimeField(_("modified at"), auto_now=True)
    ordering = models.IntegerField(_("ordering"), default=10)

    class Meta:
        ordering = ("-ordering",)
        translate = ("name", "description")
        verbose_name = _("item type")
        verbose_name_plural = _("item types")

    def __str__(self):
        return self.name

    def child_item_qs(self):
        return self.item_set.all()


class ItemQuerySet(ExtensionSelectQuerySet, HomebrewQuerySet):
    pass


class Item(HomebrewModel, metaclass=TransMeta):
    objects = ItemQuerySet.as_manager()

    name = models.CharField(_("name"), max_length=256)
    description = models.TextField(_("description"), blank=True, null=True)

    type = models.ForeignKey(ItemType, verbose_name=_("type"), on_delete=models.CASCADE)
    is_container = models.BooleanField(_("is container"), default=False)

    weight = models.DecimalField(_("weight"), decimal_places=2, max_digits=6)
    price = models.DecimalField(_("price"), decimal_places=2, max_digits=6)
    concealment = models.IntegerField(_("concealment"), default=0)
    extensions = models.ManyToManyField("rules.Extension", blank=True)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("created by"),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    charges = models.IntegerField(_("charges"), null=True, blank=True)

    modified_at = models.DateTimeField(_("modified at"), auto_now=True)
    usable_in_combat = models.BooleanField(_("usable in combat"), default=False)
    attribute = models.ForeignKey(
        "rules.Attribute",
        verbose_name=_("attribute for usage"),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    skill = models.ForeignKey(
        "rules.Skill",
        verbose_name=_("skill for usage"),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    knowledge = models.ForeignKey(
        "rules.Knowledge",
        verbose_name=_("knowledge for usage"),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    dice_roll_string = models.CharField(
        _("dice role string"),
        blank=True,
        null=True,
        max_length=10,
        help_text=_("Shows a roll button at the item if not empty."),
    )

    image = models.ImageField(
        _("image"), max_length=256, upload_to="item_images/", null=True, blank=True
    )
    image_copyright = models.CharField(
        _("image copyright"), max_length=40, blank=True, null=True
    )
    image_copyright_url = models.CharField(
        _("image copyright url"), max_length=150, blank=True, null=True
    )

    class Meta:
        translate = ("name", "description")
        verbose_name = _("item")
        verbose_name_plural = _("items")

    def __str__(self):
        return self.name

    def get_image_thumbnail(self):
        return None  # TODO: Check if it is possible to make this beautiful in _gear_item.html
        # if not self.image:
        #     return None
        # thumbnail = get_thumbnail(self.image, "100x20", crop="center")
        # return thumbnail.url


class WeaponTypeQuerySet(models.QuerySet):
    def for_extensions(self, extension_rm):
        return self.filter(
            Q(weapon__extensions__id__in=extension_rm.all())
            | Q(weapon__extensions__id__in=Extension.objects.filter(is_mandatory=True))
        ).distinct()


class WeaponType(SearchableCardListMixin, models.Model, metaclass=TransMeta):
    objects = WeaponTypeQuerySet.as_manager()

    name = models.CharField(_("name"), max_length=100)
    description = models.TextField(_("description"), blank=True, null=True)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    modified_at = models.DateTimeField(_("modified at"), auto_now=True)
    ordering = models.IntegerField(_("ordering"), default=10)

    class Meta:
        ordering = ("-ordering",)
        translate = ("name", "description")
        verbose_name = _("weapon type")
        verbose_name_plural = _("weapon types")

    def __str__(self):
        return self.name

    def get_first_image(self):
        return self.weapon_set.earliest("id").image

    def child_item_qs(self):
        return self.weapon_set.all()


RANGE_CHOICES = (
    ("-", _("hand to hand 1m")),
    ("+", _("hand to hand 2m")),
    ("s", _("short")),
    ("m", _("mid")),
    ("l", _("long")),
    ("e", _("extreme")),
)


class AttackMode(models.Model, metaclass=TransMeta):
    name = models.CharField(_("name"), max_length=100)
    dice_bonus = models.IntegerField(_("dice bonus"), default=1)
    capacity_consumed = models.IntegerField(_("capacity consumed"), default=1)

    class Meta:
        translate = ("name",)
        verbose_name = _("attack mode")
        verbose_name_plural = _("attack modes")

    def __str__(self):
        return self.name


class WeaponQuerySet(ExtensionSelectQuerySet, HomebrewQuerySet):
    pass


class Weapon(HomebrewModel, metaclass=TransMeta):
    objects = WeaponQuerySet.as_manager()

    extensions = models.ManyToManyField("rules.Extension", blank=True)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    modified_at = models.DateTimeField(_("modified at"), auto_now=True)

    is_hand_to_hand_weapon = models.BooleanField(
        _("is hand to hand weapon"), default=False
    )
    is_throwing_weapon = models.BooleanField(_("is throwing weapon"), default=False)

    name = models.CharField(_("name"), max_length=256)
    description = models.TextField(_("description"), blank=True, null=True)
    attack_modes = models.ManyToManyField(AttackMode, verbose_name=_("attack modes"))

    type = models.ForeignKey(
        WeaponType, verbose_name=_("type"), on_delete=models.CASCADE
    )

    weight = models.DecimalField(_("weight"), decimal_places=2, max_digits=6)
    price = models.DecimalField(_("price"), decimal_places=2, max_digits=8)

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("created by"),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    image = models.ImageField(
        _("image"), max_length=256, upload_to="weapon_images/", null=True, blank=True
    )
    image_copyright = models.CharField(
        _("image copyright"), max_length=40, blank=True, null=True
    )
    image_copyright_url = models.CharField(
        _("image copyright url"), max_length=150, blank=True, null=True
    )

    class Meta:
        translate = ("name", "description")
        verbose_name = _("weapon")
        verbose_name_plural = _("weapons")

    def __str__(self):
        return self.name


class Keyword(models.Model, metaclass=TransMeta):
    identifier = models.CharField(_("identifier"), max_length=40, unique=True)
    name = models.CharField(_("name"), max_length=256)
    description = models.TextField(_("description"), blank=True, null=True)
    is_rare = models.BooleanField(_("is rare"), default=False)
    is_evergreen = models.BooleanField(
        _("is evergreen"),
        default=False,
        help_text=_("Evergreen keywords are the base of the combat mechanics."),
    )
    show_in_dice_rolls = models.BooleanField(_("show in dice rolls"), default=False)
    show_in_summary = models.BooleanField(_("show in summary"), default=False)
    ordering = models.IntegerField(_("ordering"), default=10)

    class Meta:
        translate = ("name", "description")
        verbose_name = _("keyword")
        verbose_name_plural = _("keywords")
        ordering = ("-ordering",)

    def __str__(self):
        return self.name


class WeaponKeyword(models.Model):
    weapon = models.ForeignKey("armory.Weapon", on_delete=models.CASCADE)
    keyword = models.ForeignKey("armory.Keyword", on_delete=models.CASCADE)
    value = models.IntegerField(_("value"), default=1)

    class Meta:
        verbose_name = _("weapon keyword")
        verbose_name_plural = _("weapon keywords")

    def __str__(self):
        return self.keyword.name


class WeaponModificationTypeQuerySet(models.QuerySet):
    def for_extensions(self, extension_rm):
        return self.filter(
            Q(weaponmodification__extensions__id__in=extension_rm.all())
            | Q(
                weaponmodification__extensions__id__in=Extension.objects.filter(
                    is_mandatory=True
                )
            )
        ).distinct()


class WeaponModificationType(models.Model, metaclass=TransMeta):
    objects = WeaponModificationTypeQuerySet.as_manager()

    name = models.CharField(_("name"), max_length=20)
    description = models.TextField(_("description"), blank=True, null=True)
    unique_equip = models.BooleanField(
        _("unique equip"),

armory/views.py
from django.views.generic import ListView, DetailView, TemplateView

from armory.models import Item, WeaponType, RiotGearType, ItemType


class WeaponListView(ListView):
    model = WeaponType

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["navigation"] = "weapon_list"
        return context


class RiotGearListView(ListView):
    model = RiotGearType

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["navigation"] = "riot_gear_list"
        return context


class ItemListView(ListView):
    model = ItemType

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["navigation"] = "item_list"
        return context


class ItemDetailView(DetailView):
    model = Item


class MaterialOverviewView(TemplateView):
    template_name = "armory/material_overview.html"

armory/templates/armory/_navigation.html
{% load thumbnail %}
{% load world_extras %}
{% load characters_extras %}
{% load i18n %}
{% load portal_extras %}


<div class="list-group mb-3">
  {% thumbnail object.world.image "1900" as im %}
    <div class="list-group-item p-0 overflow-hidden border-bottom-0"
         style="background-image: url({{ im.url }});
                 background-repeat: no-repeat;
                 background-position: center;
                 height: 80px;
                 min-height: 100%;
                 background-size: cover;">
    </div>
  {% endthumbnail %}

  <div class="py-3 navigation-link navigation-link pointer list-group-item list-group-item-action d-flex flex-column text-center justify-content-center align-items-center"
       aria-current="true">

    <div class="mt-3 d-flex align-items-center flex-column justify-content-center">
      <span class="fw-bold">{% trans "Material" %}</span>
    </div>
  </div>

  <a class="{% if navigation == "wiki_page_with_game_values" %}active{% endif %} navigation-link pointer py-3 list-group-item list-group-item-action d-flex justify-content-between align-items-center"
     href="{% url "world:wiki_page_with_game_values" %}"
     aria-current="true">
    <div class="d-flex justify-content-center align-items-center">
      <i class="fs-5 gi-cathelineau-polar-bear"></i>
      <span class="ms-3 d-block d-lg-block">{% trans "Foes" %}</span>
    </div>
  </a>

  <a class="{% if navigation == "template_list" %}active{% endif %} navigation-link pointer py-3 list-group-item list-group-item-action d-flex justify-content-between align-items-center"
     href="{% url "rules:template_list" %}"
     aria-current="true">
    <div class="d-flex justify-content-center align-items-center">
      <i class="fas fa-fw fa-book"></i>
      <span class="ms-3 d-block d-lg-block">{% trans "Templates" %}</span>
    </div>
  </a>

  <a class="{% if navigation == "item_list" %}active{% endif %} navigation-link pointer py-3 list-group-item list-group-item-action d-flex justify-content-between align-items-center"
     href="{% url "armory:item_list" %}"
     aria-current="true">
    <div class="d-flex justify-content-center align-items-center">
      <i class="fas fa-fw fa-box"></i>
      <span class="ms-3 d-block d-lg-block">{% trans "Items" %}</span>
    </div>
  </a>

  <a class="{% if navigation == "weapon_list" %}active{% endif %} navigation-link pointer py-3 list-group-item list-group-item-action d-flex justify-content-between align-items-center"
     href="{% url "armory:weapon_list" %}"
     aria-current="true">
    <div class="d-flex justify-content-center align-items-center">
      <i class="fas fa-fw fa-khanda"></i>
      <span class="ms-3 d-block d-lg-block">{% trans "Weapons" %}</span>
    </div>
  </a>

  <a class="{% if navigation == "riot_gear_list" %}active{% endif %} navigation-link pointer py-3 list-group-item list-group-item-action d-flex justify-content-between align-items-center"
     href="{% url "armory:riot_gear_list" %}"
     aria-current="true">
    <div class="d-flex justify-content-center align-items-center">
      <i class="fas fa-fw fa-shield-alt"></i>
      <span class="ms-3 d-block d-lg-block">{% trans "Armour" %}</span>
    </div>
  </a>

  <a class="{% if navigation == "spell_origin_list" %}active{% endif %} navigation-link pointer py-3 list-group-item list-group-item-action d-flex justify-content-between align-items-center"
     href="{% url "magic:spell_origin_list" %}"
     aria-current="true">
    <div class="d-flex justify-content-center align-items-center">
      <i class="gi-lorc-fairy-wand"></i>
      <span class="ms-3 d-block d-lg-block">{% trans "Spells" %}</span>
    </div>
  </a>
</div>

armory/templates/armory/_riot_gear_protection_display.html
{% load characters_extras %}
{% for riot_gear_protection in riot_gear.get_protection %}
  {% with protection_type=riot_gear_protection.protection_type %}
    {% for i in riot_gear_protection.value|to_range %}
      <i title="{{ protection_type }}" class="{{ protection_type.icon_class }} {{ protection_type.color_class }}"></i>
    {% endfor %}
  {% endwith %}
{% endfor %}

armory/templates/armory/_weapon_widget.html
{% load i18n characters_extras rules_extras thumbnail armory_extras %}

<div class="card mb-3">
  <div class="card-body">
    <div class="row">
      <div class="col-12">
        <h4>{{ weapon }}</h4>

        {{ weapon.description|urpg_markup }}

        {% for kw in weapon.weaponkeyword_set.all %}
          <span class="fw-bold {% if kw.keyword.is_rare %}text-primary{% endif %}">{{ kw.keyword.name }}</span>
          {% color_value_span kw.value 6 %}
          <i>({{ kw.keyword.description|replace_keyword_value:kw.value }})</i><br>
        {% endfor %}

        {% if weapon.attack_modes.exists %}
          <br>
          {% for fm in weapon.attack_modes.all %}
            <button disabled class="btn btn-outline-primary mb-2 w-100">
              {{ fm.name }}<br>
            </button>
          {% endfor %}
        {% endif %}

        {% if character and add_button %}
          {% with currency_unit=character.common_currency_unit %}
            <form action="{% url 'characters:xhr_character_objects' pk=character.id object_type="weapon" %}"
                  class=" float-end add-form pt-3" method="post">
              {% csrf_token %}
              <input type="hidden" name="object_id" value="{{ weapon.id }}">
              <button class="btn btn-sm btn-primary float-end"
                      data-danger="{% trans 'Not possible' %}"
                      data-success="{% trans 'Added' %}">
                {% trans 'Add' %}
                <i class="ms-1 {{ currency_unit.fa_icon_class }} {{ currency_unit.color_class }}"></i>
                {% color_value_span weapon.price 1000 invert=True %}
              </button>
            </form>
          {% endwith %}
        {% else %}
          {% if not world_configuration %}
            {% for extension in weapon.extensions.all %}
              <span class="mt-2 badge text-muted bg-primary-subtle" title="{{ extension }}">
          <i class="m-1 {{ extension.fa_icon_class }}"></i></span>
            {% endfor %}
          {% endif %}
        {% endif %}
      </div>
    </div>
    {% if user.is_superuser %}
      <a href="{% url 'admin:armory_weapon_change' weapon.id %}"
         style="position: absolute; bottom: 2px; left: 2px; font-size: xx-small">admin</a>
    {% endif %}
  </div>
</div>

armory/templates/armory/itemtype_list.html
{% extends 'base.html' %}
{% load portal_extras %}
{% load i18n static armory_extras %}

{% block title %}{% trans 'All Items' %} - {{ block.super }}{% endblock %}
{% block in_page_title %}{% trans "Items" %}{% endblock %}
{% block in_page_subtitle %}{% endblock %}

{% block bottom_nav %}
  {% bottom_navigation_button "armory/_navigation.html" %}
{% endblock %}

{% block content %}
  <a href="{% url "armory:material_overview" %}">
    <div class="card mb-4 d-none d-md-block">
      <div class="card-body">
        <i class="fas fa-arrow-left"></i> {% trans "Back to the material page" %}
      </div>
    </div>
  </a>
  {% searchable_object_card_list object_list %}
{% endblock %}

armory/templates/armory/material_overview.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <div class="row">

    <div class="col-12 col-md-6 mb-4">
      <a href="{% url "world:wiki_page_with_game_values" %}">
        <div class="card p-4">
          <div class="card-body d-flex align-items-center justify-content-center">
            <i class="fs-1 me-2 gi-cathelineau-polar-bear"></i>
            <span class="fs-2">{% trans "Foes" %}</span>
          </div>
        </div>
      </a>
    </div>

    <div class="col-12 col-md-6 mb-4">
      <a href="{% url "rules:template_list" %}">
        <div class="card p-4">
          <div class="card-body d-flex align-items-center justify-content-center">
            <i class="fs-1 me-2 gi-delapouite-book-cover"></i>
            <span class="fs-2">{% trans "Templates" %}</span>
          </div>
        </div>
      </a>
    </div>

    <div class="col-12 col-md-6 mb-4">
      <a href="{% url "armory:item_list" %}">
        <div class="card p-4">
          <div class="card-body d-flex align-items-center justify-content-center">
            <i class="fs-1 me-2 gi-delapouite-holy-hand-grenade"></i>
            <span class="fs-2">{% trans "Items" %}</span>
          </div>
        </div>
      </a>
    </div>

    <div class="col-12 col-md-6 mb-4">
      <a href="{% url "armory:weapon_list" %}">
        <div class="card p-4">
          <div class="card-body d-flex align-items-center justify-content-center">
            <i class="fs-1 me-2 gi-delapouite-axe-sword"></i>
            <span class="fs-2">{% trans "Weapons" %}</span>
          </div>
        </div>
      </a>
    </div>

    <div class="col-12 col-md-6 mb-4">
      <a href="{% url "armory:riot_gear_list" %}">
        <div class="card p-4">
          <div class="card-body d-flex align-items-center justify-content-center">
            <i class="fs-1 me-2 gi-delapouite-viking-helmet"></i>
            <span class="fs-2">{% trans "Armour" %}</span>
          </div>
        </div>
      </a>
    </div>

    <div class="col-12 col-md-6 mb-4">
      <a href="{% url "magic:spell_origin_list" %}">
        <div class="card p-4">
          <div class="card-body d-flex align-items-center justify-content-center">
            <i class="fs-1 me-2 gi-lorc-fairy-wand"></i>
            <span class="fs-2">{% trans "Spells" %}</span>
          </div>
        </div>
      </a>
    </div>
  </div>
{% endblock %}

armory/templates/armory/riotgeartype_list.html
{% extends 'base.html' %}
{% load armory_extras %}
{% load portal_extras %}
{% load i18n static rules_extras characters_extras %}

{% block title %}{% trans 'Armour' %} - {{ block.super }}{% endblock %}
{% block in_page_title %}{% trans "Armour" %}{% endblock %}
{% block in_page_subtitle %}{% endblock %}

{% block bottom_nav %}
  {% bottom_navigation_button "armory/_navigation.html" %}
{% endblock %}

{% block javascript %}
{% endblock %}

{% block content %}
  <a href="{% url "armory:material_overview" %}">
    <div class="card mb-4 d-none d-md-block">
      <div class="card-body">
        <i class="fas fa-arrow-left"></i> {% trans "Back to the material page" %}
      </div>
    </div>
  </a>
  {% searchable_object_card_list object_list %}
{% endblock %}

armory/templates/armory/weapontype_list.html
{% extends 'base.html' %}
{% load armory_extras %}
{% load portal_extras %}
{% load i18n static rules_extras characters_extras %}

{% block title %}{% trans 'Weapons' %} - {{ block.super }}{% endblock %}
{% block in_page_title %}{% trans "Weapons" %}{% endblock %}
{% block in_page_subtitle %}{% endblock %}

{% block bottom_nav %}
  {% bottom_navigation_button "armory/_navigation.html" %}
{% endblock %}

{% block content %}
  <a href="{% url "armory:material_overview" %}">
    <div class="card mb-4 d-none d-md-block">
      <div class="card-body">
        <i class="fas fa-arrow-left"></i> {% trans "Back to the material page" %}
      </div>
    </div>
  </a>
  {% searchable_object_card_list object_list %}
{% endblock %}